# configs/dataset/cxr_multilabel.yaml

DATASET:
  NAME: 'CXR_Multi_Domain'
  LABELS_LIST: 
    - 'Atelectasis'
    - 'Cardiomegaly'
    - 'Consolidation'
    - 'Pleural Effusion'
    - 'Pneumothorax'

  # CHESTXRAY14_PATH: "/Users/admin/Working/Data/MixData/nih_14_structured"
  NIH_PATH: "/home/ngo/Working/Data/MixData/nih_14_structured"
  NIH_CSV: "validate.csv"
  NIH_IMAGE_DIR: "images"
  
  CHEXPERT_PATH: '/path/to/chexpert_data'
  CHEXPERT_CSV: 'chexpert_test_processed.csv'
  CHEXPERT_IMAGE_DIR: '' # Để trống nếu đường dẫn trong CSV là tuyệt đối/tương đối từ root

MODEL:
  NUM_CLASSES: 5

INPUT:
  SIZE: [224, 224] 
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

TEST:
  BATCH_SIZE: 32

LOADER:
  NUM_WORKS: 8