TEST:
  BATCH_SIZE: 64

OPTIM:
  METHOD: Adam
  STEPS: 1
  BETA: 0.9
  # LR: 1e-5
  LR: 0.00001
  WD: 0.

INPUT:
  # Cifar
  # SIZE: (32, 32)

  # Medical
  SIZE: [224, 224]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 2.225]

ADAPTER:
  NAME: rotta_multilabels
  RoTTA:
    NU: 0.001
    MEMORY_SIZE: 64
    UPDATE_FREQUENCY: 64
    LAMBDA_T: 1.0
    LAMBDA_U: 1.0
    ALPHA: 0.05

LOADER:
  NUM_WORKS: 4
  SAMPLER:
    TYPE: "temporal"


MODEL:
  ARCH: 'mobilenet_v3_small'
  NUM_CLASSES: 5

DATASET:
  NAME: 'CXR'
  TEST_DOMAINS: ['nih14']
  LABELS_LIST: ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Pleural Effusion', 'Pneumothorax']

  # NIH14_PATH: "/Users/admin/Working/Data/MixData/nih_14_structured"
  NIH14_PATH: "/home/ngoto/Working/Data/MixData/nih_14_structured"
  NIH14_CSV: "validate_reordered.csv" # "validate_reordered.csv"
  NIH14_IMAGE_DIR: "images"
  
  CHEXPERT_PATH: '/Users/admin/Working/Data/MixData/nih_14_structured'
  CHEXPERT_CSV: 'validate.csv'
  CHEXPERT_IMAGE_DIR: 'valid'


  ADAPTATION_MODE: "corruption"
  #Add nhieu single domain
  BASE_DOMAIN:
    # PATH: "/home/ngoto/Working/Data/CheXpert-v1.0-small"
    # CSV: "valid_split.csv" # "validate_reordered.csv, validate_reordered_subset.csv, valid_split"
    # IMAGE_DIR: "images"
    
    PATH: "/home/ngoto/Working/Data/MixData/nih_14_structured"
    CSV: "validate_reordered.csv" # "validate_reordered.csv, validate_reordered_subset.csv, valid_split"
    IMAGE_DIR: "images"

  TEST_CORRUPTIONS:
    # Các hàm thay doi tren tensor
    - gaussian_noise
    # - shot_noise
    - contrast
    - brightness
    - impulse_noise
    - elastic_transform
    
    # Các hàm cần PIL
    # - motion_blur
    # - zoom_blur
    # - glass_blur
    # - defocus_blur
    # - pixelate
    # - jpeg_compression
    # - frost
    # - snow
    # - fog

  SEVERITY: 0.01 # Mức độ nhiễu (0-5)